[package]
name = "riscv_regs"
authors = ["Rivos, Inc."]
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
tock-registers = { version = "0.7" }
riscv-decode = "0.2"
riscv_pages = { path = "../riscv-pages" }
riscv_page_tables = { path = "../riscv-page-tables" }
