[package]
name = "sbi"
authors = ["Rivos, Inc."]
license = "Apache-2.0"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.2", default-features = false }
assertions = { path = "../assertions" }
flagset = "0.4.3"

[lib]
path = "./src/sbi.rs"
