[package]
name = "riscv_page_tables"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
riscv_pages = { path = "../riscv-pages" }
page_tracking = { path = "../page-tracking" }
spin = "*"
